//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxPayment
    {
        public int ID { get; set; }
        public int TaxpayerID { get; set; }
        public int EnterpriseID { get; set; }
        public System.DateTime DateTax { get; set; }
        public string NumberTax { get; set; }
        public decimal SumAll { get; set; }
        public decimal SumTax { get; set; }
        public decimal SumPension { get; set; }
        public string ExempType { get; set; }
        public decimal Exemp { get; set; }
        public string Comment { get; set; }
    
        public virtual Enterprises Enterprises { get; set; }
        public virtual Taxpayers Taxpayers { get; set; }
    }
}
